services:
    db:
        image: postgres:15
        container_name: postgres-db
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    backend:
        build: ./backend
        container_name: flask-backend
        restart: always
        volumes: ./backend:/app
        env_file:
            - .env
        ports:
            - "5000:5000"
        depends_on:
            - db

    frontend:
        build: ./frontend
        container_name: react-frontend
        restart: always
        volumes: ./frontend:/app
        ports:
            - "80:3000"
        depends_on:
            - db
            - backend

volumes:
    pgdata:
    